import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F7F7FC",
  },
  page: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 36,
  },

  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 18,
  },
  eyebrow: {
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.8,
    color: "#9B87F5",
  },
  brand: {
    marginTop: 2,
    fontSize: 28,
    fontWeight: "900",
    letterSpacing: -1,
    color: "#231A34",
  },
  profileButton: {
    width: 48,
    height: 48,
    borderRadius: 17,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#EEEAF6",
    elevation: 2,
  },
  profileEmoji: {
    fontSize: 22,
  },
  notificationDot: {
    position: "absolute",
    right: 8,
    top: 8,
    width: 9,
    height: 9,
    borderRadius: 99,
    backgroundColor: "#F43F5E",
    borderWidth: 2,
    borderColor: "#FFFFFF",
  },

  hero: {
    minHeight: 305,
    borderRadius: 30,
    padding: 24,
    overflow: "hidden",
    backgroundColor: "#5B21B6",
    elevation: 7,
  },
  heroBubbleOne: {
    position: "absolute",
    width: 195,
    height: 195,
    borderRadius: 999,
    right: -60,
    top: -52,
    backgroundColor: "#8B5CF6",
  },
  heroBubbleTwo: {
    position: "absolute",
    width: 145,
    height: 145,
    borderRadius: 999,
    left: -70,
    bottom: -68,
    backgroundColor: "#C4B5FD",
    opacity: 0.25,
  },
  heroTag: {
    alignSelf: "flex-start",
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.14)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.19)",
  },
  heroTagText: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1,
    color: "#F5F3FF",
  },
  heroTitle: {
    marginTop: 19,
    maxWidth: "95%",
    fontSize: 29,
    lineHeight: 35,
    fontWeight: "900",
    letterSpacing: -0.8,
    color: "#FFFFFF",
  },
  heroSubtitle: {
    marginTop: 11,
    maxWidth: "94%",
    fontSize: 13,
    lineHeight: 20,
    color: "#EDE9FE",
  },
  heroStats: {
    marginTop: 24,
    paddingVertical: 14,
    paddingHorizontal: 10,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  statItem: {
    minWidth: 76,
    alignItems: "center",
  },
  statNumber: {
    fontSize: 19,
    fontWeight: "900",
    color: "#FFFFFF",
  },
  statLabel: {
    marginTop: 2,
    fontSize: 10,
    color: "#DDD6FE",
  },
  statDivider: {
    width: 1,
    height: 28,
    backgroundColor: "rgba(255,255,255,0.20)",
  },

  searchBox: {
    height: 59,
    marginTop: 18,
    paddingLeft: 16,
    paddingRight: 8,
    borderRadius: 19,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#EEEAF6",
    elevation: 2,
  },
  searchIcon: {
    fontSize: 25,
    color: "#8D849A",
    transform: [{ rotate: "-18deg" }],
  },
  searchInput: {
    flex: 1,
    marginLeft: 9,
    fontSize: 14,
    color: "#2D2340",
  },
  filterIconBox: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#7C3AED",
  },
  filterIcon: {
    fontSize: 20,
    color: "#FFFFFF",
  },

  sectionHeading: {
    marginTop: 29,
    marginBottom: 14,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  sectionEyebrow: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1.7,
    color: "#A78BFA",
  },
  sectionTitle: {
    marginTop: 3,
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: -0.5,
    color: "#241A36",
  },
  sectionHint: {
    fontSize: 11,
    fontWeight: "700",
    color: "#91889E",
  },

  categoryList: {
    gap: 9,
    paddingRight: 20,
  },
  categoryChip: {
    paddingHorizontal: 17,
    paddingVertical: 11,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#ECE8F4",
    backgroundColor: "#FFFFFF",
  },
  categoryChipActive: {
    backgroundColor: "#21182F",
    borderColor: "#21182F",
  },
  categoryChipText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#746B81",
  },
  categoryChipTextActive: {
    color: "#FFFFFF",
  },

  featuredCard: {
    marginTop: 24,
    minHeight: 184,
    borderRadius: 26,
    overflow: "hidden",
    flexDirection: "row",
    backgroundColor: "#EEE9FF",
    borderWidth: 1,
    borderColor: "#E1D8FE",
  },
  featuredLeft: {
    flex: 1.45,
    padding: 19,
    zIndex: 2,
  },
  featuredBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
  },
  featuredBadgeText: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.8,
    color: "#6D28D9",
  },
  featuredTitle: {
    marginTop: 14,
    fontSize: 20,
    lineHeight: 25,
    fontWeight: "900",
    color: "#2E1065",
  },
  featuredDescription: {
    marginTop: 7,
    fontSize: 11,
    lineHeight: 17,
    color: "#6D5E87",
  },
  featuredDate: {
    marginTop: 14,
    fontSize: 11,
    fontWeight: "800",
    color: "#5B21B6",
  },
  featuredArtwork: {
    width: 112,
    alignItems: "center",
    justifyContent: "center",
  },
  artCircleOuter: {
    width: 148,
    height: 148,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#C4B5FD",
    transform: [{ translateX: 29 }],
  },
  artCircleInner: {
    width: 78,
    height: 78,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#7C3AED",
  },
  artEmoji: {
    fontSize: 34,
  },

  resultCount: {
    minWidth: 34,
    height: 34,
    paddingHorizontal: 10,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EDE9FE",
  },
  resultCountText: {
    fontWeight: "900",
    color: "#6D28D9",
  },

  eventList: {
    gap: 14,
  },
  eventCard: {
    overflow: "hidden",
    flexDirection: "row",
    borderRadius: 24,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#EEEAF6",
    elevation: 3,
  },
  eventAccent: {
    width: 6,
  },
  eventBody: {
    flex: 1,
    padding: 17,
  },
  eventTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  eventIcon: {
    width: 46,
    height: 46,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  eventEmoji: {
    fontSize: 22,
  },
  categoryBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#F5F3FF",
  },
  categoryBadgeText: {
    fontSize: 9,
    fontWeight: "900",
    color: "#6D28D9",
  },
  eventTitle: {
    marginTop: 14,
    fontSize: 19,
    fontWeight: "900",
    letterSpacing: -0.3,
    color: "#21192F",
  },
  eventDescription: {
    marginTop: 6,
    marginBottom: 11,
    fontSize: 12,
    lineHeight: 18,
    color: "#7A7188",
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 7,
  },
  infoIcon: {
    width: 24,
    fontSize: 14,
  },
  infoText: {
    flex: 1,
    fontSize: 11,
    color: "#6B7280",
  },
  eventFooter: {
    marginTop: 15,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: "#F1EEF6",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  seatCaption: {
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 1,
    color: "#A49CAD",
  },
  seatValue: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: "900",
    color: "#362B48",
  },
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  detailButton: {
    height: 40,
    paddingHorizontal: 12,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F5F3FF",
  },
  detailButtonText: {
    fontSize: 10,
    fontWeight: "900",
    color: "#6D28D9",
  },
  joinButton: {
    height: 40,
    paddingHorizontal: 13,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  joinButtonText: {
    fontSize: 10,
    fontWeight: "900",
    color: "#FFFFFF",
  },

  emptyState: {
    padding: 28,
    borderRadius: 24,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#EEEAF6",
  },
  emptyEmoji: {
    fontSize: 32,
  },
  emptyTitle: {
    marginTop: 10,
    fontSize: 17,
    fontWeight: "900",
    color: "#2A2039",
  },
  emptyText: {
    marginTop: 5,
    textAlign: "center",
    fontSize: 11,
    lineHeight: 17,
    color: "#8B8296",
  },

  cta: {
    marginTop: 26,
    padding: 18,
    borderRadius: 24,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#21182F",
  },
  ctaIcon: {
    width: 52,
    height: 52,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#7C3AED",
  },
  ctaEmoji: {
    fontSize: 23,
  },
  ctaContent: {
    flex: 1,
    marginLeft: 14,
  },
  ctaTitle: {
    fontSize: 15,
    fontWeight: "900",
    color: "#FFFFFF",
  },
  ctaText: {
    marginTop: 4,
    fontSize: 10,
    lineHeight: 16,
    color: "#CEC6D9",
  },

  footer: {
    marginTop: 25,
    textAlign: "center",
    fontSize: 9,
    fontWeight: "700",
    color: "#A69DAD",
  },
});
